#!/bin/bash
# Скрипт для получения приватного ключа Finik с удаленного сервера

echo "=== Способ 1: Просмотр .env файла на сервере ==="
echo ""
echo "Подключитесь к серверу:"
echo "  ssh root@ваш_сервер_IP"
echo ""
echo "Затем выполните:"
echo "  cd ~/stud"
echo "  grep 'FINIK_PRIVATE_KEY_PEM' .env"
echo ""
echo "Или просмотрите весь .env:"
echo "  cat .env | grep -A 1 'FINIK_PRIVATE_KEY_PEM'"
echo ""
echo "=== Способ 2: Если ключ в отдельном файле ==="
echo ""
echo "На сервере выполните:"
echo "  cat ~/stud/finik_private.pem"
echo ""
echo "Или найдите файл:"
echo "  find ~ -name '*finik*private*.pem' 2>/dev/null"
echo ""
echo "=== Способ 3: Копирование файла через SCP ==="
echo ""
echo "С вашего локального компьютера выполните:"
echo "  scp root@ваш_сервер_IP:~/stud/.env ./"
echo ""
echo "Или если ключ в отдельном файле:"
echo "  scp root@ваш_сервер_IP:~/stud/finik_private.pem ./"
echo ""

